import { WorkoutProgram } from './types';

export const initialProgram: WorkoutProgram = {
  id: 'program_mvp',
  userId: 'user_demo',
  title: 'Hipertrofia 2026',
  description: 'Programa inicial para validar a organização semanal do treino.',
  goal: 'hipertrofia',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  weeks: [
    {
      id: 'week_1',
      title: 'Semana 1 — Adaptação',
      weekNumber: 1,
      notes: 'Foco em técnica, amplitude e constância.',
      days: [
        {
          id: 'day_push',
          title: 'Segunda — Peito e Tríceps',
          dayOfWeek: 'Segunda-feira',
          order: 1,
          status: 'not_started',
          exercises: [
            {
              id: 'ex_supino_reto',
              name: 'Supino reto',
              muscleGroup: 'Peitoral',
              sets: '4',
              reps: '8-10',
              load: '60kg',
              restSeconds: 90,
              notes: 'Controlar a descida.',
              order: 1,
              completed: false,
            },
            {
              id: 'ex_supino_inclinado',
              name: 'Supino inclinado',
              muscleGroup: 'Peitoral',
              sets: '3',
              reps: '10',
              load: '45kg',
              restSeconds: 75,
              order: 2,
              completed: false,
            },
            {
              id: 'ex_triceps_corda',
              name: 'Tríceps corda',
              muscleGroup: 'Tríceps',
              sets: '3',
              reps: '12',
              load: '25kg',
              restSeconds: 60,
              order: 3,
              completed: false,
            },
          ],
        },
        {
          id: 'day_pull',
          title: 'Terça — Costas e Bíceps',
          dayOfWeek: 'Terça-feira',
          order: 2,
          status: 'not_started',
          exercises: [
            {
              id: 'ex_puxada',
              name: 'Puxada frente',
              muscleGroup: 'Costas',
              sets: '4',
              reps: '8-10',
              load: '55kg',
              restSeconds: 90,
              order: 1,
              completed: false,
            },
            {
              id: 'ex_remada',
              name: 'Remada baixa',
              muscleGroup: 'Costas',
              sets: '3',
              reps: '10-12',
              load: '50kg',
              restSeconds: 75,
              order: 2,
              completed: false,
            },
          ],
        },
        {
          id: 'day_legs',
          title: 'Quarta — Pernas',
          dayOfWeek: 'Quarta-feira',
          order: 3,
          status: 'not_started',
          exercises: [
            {
              id: 'ex_agachamento',
              name: 'Agachamento livre',
              muscleGroup: 'Pernas',
              sets: '4',
              reps: '6-8',
              load: '80kg',
              restSeconds: 120,
              notes: 'Manter tronco firme.',
              order: 1,
              completed: false,
            },
            {
              id: 'ex_leg_press',
              name: 'Leg press',
              muscleGroup: 'Pernas',
              sets: '3',
              reps: '12',
              load: '160kg',
              restSeconds: 90,
              order: 2,
              completed: false,
            },
          ],
        },
      ],
    },
  ],
};
